//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SachDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorContribute
    {
        public long ID { get; set; }
        public long bookId { get; set; }
        public long authorId { get; set; }
        public string role { get; set; }
    
        public virtual BookAuthor BookAuthor { get; set; }
        public virtual Book Book { get; set; }
    }
}
